### ISSUE TITLE
Questions about using tools

### ISSUE THREAD

**Issue by Connor-fire** [wsong-nj/PermDroid#1]
In the fourth step of "Dynamic Analysis Module" in the readme file, does ape.jar refer to static/ape.jar? I don't think it will take 1 minute to execute "adb push ape.jar /data/local/tmp/" command. This step is very confusing。
Looking forward to your reply.

**Comment by wsong-nj** [comment]
Sorry. APE is another tool only for the experimental comparison. You can neglect this step if you do not compare it with PermDroid. Now, the readme file is updated.
