### ISSUE TITLE
Confusion about source code

### ISSUE THREAD

**Issue by Connor-fire** [wsong-nj/PermDroid#2]
I think there is an error shown in the picture in "src/dynamic_Test_util/startMyDynamic.java". We should be running PermDroid, not another tool, APE.
Looking forward to your reply.
![image](https://user-images.githubusercontent.com/55130798/197964862-712c92ca-c457-49e1-b64c-2522471d3259.png)

**Comment by wsong-nj** [comment]
The previously uploaded readme file and code misused the version for comparison. 
The java file is for running different tools in the experimental comparison, and you can comment out those you do not want to run. Please download the latest version (the picture was also updated). Thank you.
